name: smarthome
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vibration: ^1.8.4
  intl: ^0.19.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  audioplayers: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/Sounds/
    - assets/images/MainDoor.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/App_logo.webp"

