// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJuvQHyX4DmXbBzWAsNGXVL0dzx53VGZI',
    appId: '1:326864355809:ios:58bba3883eda76171612a0',
    messagingSenderId: '326864355809',
    projectId: 'fedoma-smarthome',
    storageBucket: 'fedoma-smarthome.appspot.com',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1nQQzIiJ77tQYOz15iXJKtd0PdXubo24',
    appId: '1:326864355809:android:e6720c9f40faf78c1612a0',
    messagingSenderId: '326864355809',
    projectId: 'fedoma-smarthome',
    storageBucket: 'fedoma-smarthome.appspot.com',
  );
}
